### PR TITLE
Remove a space

### PR DESCRIPTION
**Pull request by stefanheimes**
Remove a space at the end of line. This should solve problems with "empty"-function

### CODE REVIEW

**Comment by zonky2** [comment]
> This should solve problems with "empty"-function

... we had an problem?

**Comment by discordier** [comment]
Erm... PR closed without merge but attached to a milestone? @stefanheimes please decide what should happen with this PR.

**Comment by zonky2** [comment]
my be because @stefanheimes work with branch https://github.com/MetaModels/attribute_url/commit/6c744065e6093fab6356ed03b35552174318cc87 and PR ?

**Comment by discordier** [comment]
Ah, ok, missed that one. So this has been merged. :+1:

**Pull request closed without merging**
